export const workExpDesk = [
    {
        cardBgColor: "#168aad",
        cardTextColor: "#000",
        date: "2017-2018",
        iconBgColor: "#168aad",
        icon: "study",
        workTitle: "12th (CBSE)",
        workLocation: "Kendriya Vidyalaya, Sambalpur",
        description: "Recieved Gold in Table Tennis and Silver in Badminton",
    },
    {
        cardBgColor: "#168aad",
        cardTextColor: "#000",
        date: "2018-2022",
        iconBgColor: "#168aad",
        icon: "study",
        workTitle: "B.Tech in Electronics & Communication Engineering",
        workLocation: "Manipal University, Jaipur",
        description: "Built a Smart Animal Feeding System with 3 of my friends",
    },
    {
        cardBgColor: "#34a0a4",
        cardTextColor: "#000",
        date: "July'21-Aug'21",
        iconBgColor: "#34a0a4",
        icon: "work",
        workTitle: "Trainee",
        workLocation: "Larsen & Toubro, Delhi",
        description: "Presented a project on Industry 4.0 that focuses on AI//ML, IoT, Cloud Computing for various production facilities.",
    },
    {
        cardBgColor: "#34a0a4",
        cardTextColor: "#000",
        date: "Feb'22 - July'22",
        iconBgColor: "#34a0a4",
        icon: "work",
        workTitle: "Java Developer Intern",
        workLocation: "Ericsson India, Remote",
        description: "Developed a web-service using JAVA and Maven that uses SOAP for requesting and responding data from client to server and vice-versa, stores and manipulates the data and sends it back to the client as per the request.",
    },
    {
        cardBgColor: "#34a0a4",
        cardTextColor: "#000",
        date: "Aug'22 - March'23",
        iconBgColor: "#34a0a4",
        icon: "work",
        workTitle: "Domain Support Specialist",
        workLocation: "Ericsson India, Noida-IN",
        description: "Worked as a software support engineer for the client MTNL (Nigeria & Uganda).",
    },
    {
        cardBgColor: "#34a0a4",
        cardTextColor: "#000",
        date: "March'23 - May'24",
        iconBgColor: "#34a0a4",
        icon: "work",
        workTitle: "Software Engineer",
        workLocation: "Ericsson India, Noida-IN",
        description: "Worked as automation engineer for the client Du (Dubai). Developed an Autocaller app for the support engineers that notifies them about system failures.",
    },
    {
        cardBgColor: "#bfd200",
        cardTextColor: "#000",
        date: "May'24 - Present",
        iconBgColor: "#bfd200",
        icon: "code",
        workTitle: "Freelance",
        workLocation: "Remote",
        description: "Developed a dashboard application for Intel.",
    },
]

export const workExpMob = [

    {
        cardBgColor: "#168aad",
        cardTextColor: "#000",
        date: "2018-2022",
        iconBgColor: "#168aad",
        icon: "study",
        workTitle: "B.Tech in Electronics & Communication Engineering",
        workLocation: "Manipal University, Jaipur",
        description: "Built a Smart Animal Feeding System with 3 of my friends",
    },
    {
        cardBgColor: "#34a0a4",
        cardTextColor: "#000",
        date: "Aug'22 - May'24",
        iconBgColor: "#34a0a4",
        icon: "work",
        workTitle: "Software Engineer",
        workLocation: "Ericsson India, Noida-IN",
        description: "Worked as automation engineer for the client Du (Dubai). Developed an Autocaller app for the support engineers that notifies them about system failures.",
    },
    {
        cardBgColor: "#bfd200",
        cardTextColor: "#000",
        date: "May'24 - Present",
        iconBgColor: "#bfd200",
        icon: "code",
        workTitle: "Freelance",
        workLocation: "Remote",
        description: "Developed a dashboard application for Intel.",
    },
]